# -*- coding: utf-8 -*-
"""COVID-19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/178OGWOd_CX4WigtBwWa6kv7P9KmP5_ut
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import subprocess
from datetime import datetime

if not os.path.exists("covid-19-data"):
    subprocess.run(["git", "clone", "https://github.com/nytimes/covid-19-data.git"])
else:
    subprocess.run(["git", "pull"], cwd="covid-19-data")

df = pd.read_csv("covid-19-data/us-counties.csv")

def plot_county(county, axis, min_cases=10, lineweight=1):
    county_data = df.loc[df.county==county]
    dates = county_data.date.to_numpy()
    cases = county_data.cases.to_numpy()
    new_cases = cases[1:] - cases[:-1]
    new_cases = np.insert(new_cases, 0, 0)
    mask = new_cases > 0
    new_cases = new_cases[mask]
    cases = cases[mask]
    dates = dates[mask]
    if len(cases) > 0 and cases[-1] > min_cases:
      axis.loglog(cases, new_cases, label=county, linewidth=lineweight)

def counties_by_num_cases(df):
  counties = df.county.unique()
  cases = []
  for county in counties:
    cases.append(df.loc[df.county==county].cases.to_numpy()[-1])
  county_cases = list(zip(counties, cases))
  county_cases = sorted(county_cases, key=lambda x: x[1])[::-1]
  counties = [x[0] for x in county_cases]
  return counties

def latest_date(df):
  return df.date.max()
def get_time():
  import pytz
  utc = pytz.timezone('UTC')
  now = utc.localize(datetime.utcnow())
  la = pytz.timezone('America/Los_Angeles')
  local_time = now.astimezone(la)
  return local_time.strftime("%m/%d/%Y, %H:%M:%S %Z")

num_counties_to_plot=10
fig, ax0 = plt.subplots(nrows=1, ncols=1,figsize=[8, 8])
counties = counties_by_num_cases(df)
for county in counties[:num_counties_to_plot]:
  plot_county(county, min_cases=300, axis=ax0)
my_counties = ["Santa Clara", "Marin", "San Francisco"]
for county in my_counties:
    plot_county(county, axis=ax0, lineweight=4)
ax0.set_xlabel("Total Cases")
ax0.set_ylabel("New Cases")
ax0.set_title(f"Top {num_counties_to_plot} counties in the USA, by number of cases, as of {latest_date(df)}\nScript last run {get_time()}")
ax0.grid()
l=ax0.legend(loc="upper left")
fig.savefig("covid_plot.jpg")
#plt.show()

